### ISSUE TITLE
Need the ability to install an agent, but not register it 

### ISSUE THREAD

**Issue by paulcalabro** [wazuh/wazuh-puppet#106]
Sometimes it's necessary to install the Wazuh agent, but not register it with a manager. For example, when working with Amazon Machine Images (AMIs). You want to reduce the time it takes to install the agent by baking the installation into the image, however, you don't want to have duplicate client.keys files by doing registration at the time of image creation. Having the ability to filter these tasks would be useful, perhaps with tags.

**Comment by manuasir** [comment]
Hi @paulcalabro,

Sorry for the late response. Indeed, this behavior is pretty desirable, so we will schedule and approach the task as soon as possible. Thanks for your valuable opinion!

Cheers

**Comment by jm404** [comment]
Hi @paulcalabro,@fe80,@pvk123,@JPLachance

Sorry for the very late response,

The registration sections have been modified to allow the installation of agents without registering them.

You can check the changes at : [#63e1a13](https://github.com/wazuh/wazuh-puppet/commit/63e1a1390edbaef4387c4397c16636514525eeaa)

_Note: Although the agent is not registered, the `ossec.conf` file is configured._

When not enabled (not set to "yes"), `agent.pp` will install Wazuh Agent but **will not** attempt to register it. Also, the service will be stopped and disabled.

In the opposite case, the `agent-auth` command will be generated using defined registration parameters. Then it will be executed in order to properly register the agent on the manager.

You can have a look at this change and others in the [Release 3.9.1_7.1.0](https://github.com/wazuh/wazuh-puppet/issues/123)

Best regards!

Jose

**Comment by manuasir** [comment]
Done here #128
