### ISSUE TITLE
problem in  remote commands for Wazuh agents

### ISSUE THREAD

**Issue by ossecowner** [wazuh/wazuh-puppet#127]
hello  @manuasir 
I tried to remote commands for Wazuh agents. I enabled this flag by adding the following line to the file /var/ossec/etc/local_internal_options.conf in the agent:
`wazuh_command.remote_commands=1`
 and in the agent.conf in server i wrote:
 ```
<wodle name="command">
  <disabled>no</disabled>
  <tag>test</tag>
  <command>/bin/bash /root/script.sh</command>
  <interval>10</interval>
  <ignore_output>no</ignore_output>
  <run_on_start>yes</run_on_start>
  <skip_verification>yes</skip_verification>
  <timeout>0</timeout>
  </wodle>
```
 I created script.sh in **server**  in path  /root/script.sh and in it:

```
#!/bin/bash

hostname
```
and in server  I wrote:
`chown ossec:ossec script.sh`
 but in the /var/ossec/logs/ossec.log in agent side we have:
`2019/06/15 11:56:13 wazuh-modulesd:command: ERROR: Command 'test' failed.`

and server and agent are synchronized.
do you know what is it's problem?
Thank you so much.

**Comment by jm404** [comment]
Hi @ossecowner,

The `wazuh-modulesd` daemon executes scripts and commands on agents. In your configuration, the `script.sh` is in the server but must be in the agent in order to properly work.

I ran the same configuration:

**`/var/ossec/etc/shared/default/agent.conf`:**

```<agent_config name="agent">
 <wodle name="command">
 <disabled>no</disabled>
 <tag>test</tag>
 <command>/bin/bash /root/script.sh</command>
 <interval>10</interval>
 <ignore_output>no</ignore_output>
 <run_on_start>yes</run_on_start>
 <skip_verification>yes</skip_verification>
 <timeout>0</timeout>
 </wodle>
</agent_config>
```

**`script.sh`:**
```
#!/bin/bash

hostname
```


It works properly, just ensure to create the `script.sh` file **in every agent** you want to run it.

![image](https://user-images.githubusercontent.com/46649922/59587617-f55e0180-90e5-11e9-9437-81b33e0eec57.png)

You can check [Wazuh Centralized Configuration](https://documentation.wazuh.com/3.9/user-manual/reference/centralized-configuration.html) for more information about how to configure agents and verify `agent.conf`.

Also be sure that the name of your agent in `/var/ossec/etc/shared/default/agent.conf` is correct.

Please let me know if you have further questions or concerns.

Best regards!

Jose

**Comment by ossecowner** [comment]
hello @jm404 
 I read your answer.thank you for your reply. I read your [blog post](https://wazuh.com/blog/scheduling-remote-commands-for-wazuh-agents/) , but I find this Sentence in it:
` Scripts can also be received from the manager as the shared configuration, but they lose the execution permissions and the owner and group should be switched to ossec:ossec.`
I want to run the command that they are in the server. I dont have access to agents.
thanks for your guide.

**Comment by jm404** [comment]
Hi @ossecowner,

I elaborated my previous reply thinking that you must execute a script under de `/root/` folder so I think I missunderstood you.

If the `/root/` folder is not a must for you and you simply want to distribute a script to agents and execute it, you can execute the following steps:

IMPORTANT:

Wazuh-Manager will **only** share the files at `/var/ossec/etc/shared` . In this folder the groups folders are placed, in my case only the `default` group folder.

In order to copy a script from Manager to Agent, such script must be in the folder of the group that agent belongs.

In my case, my Agent belongs to `default` group, so the script will be placed in `/var/ossec/etc/shared/default`

You can find all information about this in the [Agent groups](https://documentation.wazuh.com/3.9/user-manual/reference/centralized-configuration.html#agent-groups) section of the documentation.

### Create the script

```sudo echo "hostname" > /var/ossec/etc/shared/default/script.sh```

### Configure /var/ossec/etc/shared/default/agent.conf
```
 <wodle name="command">
 <disabled>no</disabled>
 <tag>test</tag>
 <command>/bin/bash /var/ossec/etc/shared/script.sh</command>
 <interval>10</interval>
 <ignore_output>no</ignore_output>
 <run_on_start>yes</run_on_start>
 <skip_verification>yes</skip_verification>
 <timeout>0</timeout>
 </wodle>
</agent_config>
```
### Enable remote commands on agent

```sudo echo "wazuh_command.remote_commands=1" >> /var/ossec/etc/local_internal_options.conf```

### Restart Wazuh-Manager 

```sudo /var/ossec/bin/ossec-control```


Then the Agent will restart itself to apply the new configuration.

If you grep the `/var/ossec/etc/shared` folder of the Agent you will find the `script.sh` file

![image](https://user-images.githubusercontent.com/46649922/59601561-a07db380-9104-11e9-8790-b8cabeff0e6a.png)

Note that execution permissions are not enabled and the owner is `ossec:ossec`, don' t worry about that, that's correct.

If you check logs you will find that the command is being executed.

![image](https://user-images.githubusercontent.com/46649922/59601678-0a965880-9105-11e9-8c3f-da14953b61cf.png)


Hope this helps to solve your problem,

Best regards!

Jose

**Comment by ossecowner** [comment]
hi @jm404 
I did what you said exactly , script.sh goes to agent from manager and its okay.  but it is not executed , output log is below : 
/var/ossec/logs/ossec.log

the command is started but never finished 
and the output of command is not shown in kibana 
```
2019/06/18 11:21:32 wazuh-modulesd:command: INFO: Module command:test started
2019/06/18 11:22:02 wazuh-modulesd:command: INFO: Module command:test started
2019/06/18 11:23:01 wazuh-modulesd:command: INFO: Module command:test started
2019/06/18 11:40:02 ossec-logcollector[4465] read_syslog.c:87 at read_syslog():              DEBUG: Reading syslog message: 'Jun 18 11:40:01 localhost CRON[19726]: (smmsp) C             MD (test -x /etc'...
2019/06/18 12:00:02 ossec-logcollector[4465] read_syslog.c:87 at read_syslog():              DEBUG: Reading syslog message: 'Jun 18 12:00:01 localhost CRON[3427]: (smmsp) CM             D (test -x /etc/'...


```

**Comment by jm404** [comment]
HI @ossecowner,

As a first step, let me recommend you to test the script running it locally to make sure it works.

To check if the command is being executed in the Agents, I suggest you use `/var/ossec/bin/wazuh-modulesd -fd` which will start the module in debug mode.

In order to create an alert in Kibana, you need to create a decoder that will parse the output of the command execution. After that, create a rule that will trigger and generate the alert in Kibana.

Such process is described in the blog post mentioned before, that you can check here:
-  https://wazuh.com/blog/scheduling-remote-commands-for-wazuh-agents/

Under the **Use case: Monitoring the disk usage on your agents** you can find detailed info about the steps I mentioned.

Be caution when creating the rules and matching them, regex can be tricky sometimes.

If you need 

Best regards,

Jose

**Comment by ossecowner** [comment]
Dear @jm404  
I set `agent.debug=2`  in 

> /var/ossec/etc/local_internal_options.conf

 and the result was:
```
2019/06/18 15:04:54 wazuh-modulesd:command[23447] wm_command.c:179 at wm_command_main(): DEBUG: Starting command 'test'.
2019/06/18 15:04:54 wazuh-modulesd:command[23447] wm_command.c:218 at wm_command_main(): DEBUG: Command 'test' finished.
```
so it is correct. but I want to see the result on kibana and you seid it is possible with defining decoder and rule, ok. I wrote these rule and decoder for result of script.sh:
```
#!/bin/bash
hostname
```
decoder:
```
<decoder name="test">
   <prematch></prematch>
   <regex offset="after_prematch">(\s+)</regex>
   <order>hostname</order>
</decoder>
```
rule:
```
<group name="command">
<rule id="100003" level="3">
<decoded_as>test</decoded_as>
<description> this is test </description>
</rule>
</group>
```
`then :  systemctl restart wazuh-manager`
 but I don't see the result in kibana .do you know what is it's reason ? 
Thank you for your patience.  👍

**Comment by jm404** [comment]
Hi @ossecowner,

Your line `<regex offset="after_prematch">(\s+)</regex>` is only matching whitespaces. You can have a look at [Wazuh Regex](https://documentation.wazuh.com/3.x/user-manual/ruleset/ruleset-xml-syntax/regex.html) if you need more info about this.

It's also recommended to use some kind of prematch in our scripts output so we can easily match them without having to elaborate a complex regex.

According to your example, I elaborated the following decoder and rule:

**Decoder:**
```
<decoder name="hostname">
    <prematch>^hostname: </prematch>
    <regex offset="after_prematch">\S+</regex>
    <order>hostname</order>
</decoder>
```

**Rule:**

```
<group name="local,monitor,stats">

  <rule id="100001" level="5">
    <decoded_as>hostname</decoded_as>
    <description>Checking hostname</description>
  </rule>

</group>
```

*Important note: The default alert level is 3, so be sure to specify a higher level in your rules.*

**Script:**
```
#!/bin/bash

hostname | while IFS= read -r line;
do
  echo "hostname: "$line
done
```


After configuring that, make sure to restart Wazuh-Manager and check that script properly propagated to manager by catting it in the agent side for example.

Then, you can check your Wazuh-Manager logs to see that the alert is being generated.

![image](https://user-images.githubusercontent.com/46649922/59683852-2ff49680-91d9-11e9-9b53-112557e2277d.png)

In Kibana:

![image](https://user-images.githubusercontent.com/46649922/59684030-7f3ac700-91d9-11e9-84cc-adda4eaeb335.

Feel free to share any question or concerns!

Best Regars,

Jose

**Comment by ossecowner** [comment]
hi @jm404 
oh yes I wrote \s+ Instead \S+ .I modified the rule and decoder and now it's ok.  Thank you for your help and kindness.  i'm beginner so I have a long way to go and learn.
Best Regards.

**Comment by jm404** [comment]
Hi @ossecowner,

Glad to help!

As always, if you have any other question or concern feel completely free to open a new Issue or PR

Best regards,

Jose
