### ISSUE TITLE
using  wazuh for checking ISO 27001

### ISSUE THREAD

**Issue by ossecowner** [wazuh/wazuh-puppet#130]
Hi daer @jm404  @manuasir
I know we can use wazuh for PCI DSS and GDPR.  do you know how can I use wazuh for checking ISO 27001? 
 thank you.

**Comment by ossecowner** [comment]
excuseme, I have another question a bout this. According to (https://documentation.wazuh.com/3.x/pci-dss/policy-monitoring.html) for pci_dss i did this step:

in path" /var/ossec/etc/rootcheck  " I wrote :
 `cp  system_audit_ssh.txt    /var/ossec/etc/shared/soc/`
 and in new path:
`chown ossec:ossec system_audit_ssh.txt`

 in  /var/ossec/etc/shared/soc/agent.conf:
```
<rootcheck>
    <system_audit>/var/ossec/etc/shared/system_audit_ssh.txt<system_audit>
</rootcheck>
```
then  `systemctl restart wazu-manager.service`
so if it's correct i shoud see log PCI_DSS: 2.2.4 in kibana when I ssh to agents of soc group. but I can't  see log in kibana. why ?

thank you.

**Comment by ossecowner** [comment]
excuseme, I have another question a bout this. According to (https://documentation.wazuh.com/3.x/pci-dss/policy-monitoring.html) for pci_dss i did this step:

in path" /var/ossec/etc/rootcheck  " I wrote :
 `cp  system_audit_ssh.txt    /var/ossec/etc/shared/soc/`
 and in new path:
`chown ossec:ossec system_audit_ssh.txt`

 in  /var/ossec/etc/shared/soc/agent.conf:
```
<rootcheck>
    <system_audit>/var/ossec/etc/shared/system_audit_ssh.txt<system_audit>
</rootcheck>
```
then  `systemctl restart wazu-manager.service`
so if it's correct i shoud see log PCI_DSS: 2.2.4 in kibana when I ssh to agents of soc group. but I can't  see log in kibana. why ?

thank you.

**Comment by jm404** [comment]
Hi @ossecowner,

Although we currently don't have a mapping checklist for ISO 27001, can do a huge work with A.5-A.18 controls among others (https://en.wikipedia.org/wiki/Security_controls) 

### Policy Monitoring

Wazuh-Manager stores the `system_audit_ssh.txt` under `/var/ossec/etc/shared/etc/<AGENT_GROUP_NAME>`. Note that by default, all agents are added to `default` group unless you specify another one.

On agents, such configuration file will be at `/var/ossec/etc/shared`. It's not needed to copy to another subfolder.

PCI_DDS policy scan files are specified in the `/var/ossec/etc/ossec.conf` under the `sca` block. Make sure it's activated and properly configured:

![image](https://user-images.githubusercontent.com/46649922/60790085-e86e8400-a160-11e9-9d82-620e12c3d543.png)

*Note: Your configuration may vary, i'm using Centos 7 so RHEL 7 policy is preconfigured*

By default SCA is enabled so the scan should automatically be done, if not, configure it and restart Wazuh-Manager.

To check if the evaluation has been done:

```cat /var/ossec/logs/ossec.log | grep ssh ```

![image](https://user-images.githubusercontent.com/46649922/60790160-18b62280-a161-11e9-8b15-76c5b4909a39.png)

On Kibana you can check for such alerts: 

```rule.pci_dss :*```

![image](https://user-images.githubusercontent.com/46649922/60790213-413e1c80-a161-11e9-81b5-6adec04ca5bd.png)

### OpenScap

The steps required to enable and use OpenSCAP are:

#### Install openscap:

Centos / RHEL:

```sudo yum install openscap scap-security-guide -y ```


Ubuntu / Debian:

``` apt-get install libopenscap8 xsltproc -y ```

#### Enable OpenScap in ossec.conf

Navigate to the open-scap wodle and make sure it's activated:

![image](https://user-images.githubusercontent.com/46649922/60790671-4b144f80-a162-11e9-8913-351953e35d37.png)

Now restart Manager and you can check if it's executing the evaluation by checking the `ossec.log` file:

``` cat /var/ossec/logs/ossec.log | grep oscap ```

This will give you an output like this:

![image](https://user-images.githubusercontent.com/46649922/60790766-87e04680-a162-11e9-8f55-235bbd0caccc.png)

Note it takes few minutes to complete.

In order to visualize such alerts, you can enable the Openscap module in Kibana Extensions.

![image](https://user-images.githubusercontent.com/46649922/60790905-d4c41d00-a162-11e9-9220-72f50b77c26c.png)

So in your **Overview -> OpenSCAP** section you can check a summary of such alerts.

![image](https://user-images.githubusercontent.com/46649922/60790952-f1605500-a162-11e9-916d-d3c714a6a82d.png)


Hope this helps! Don't hesitate to ask if you still have some questions

Best regards,

Jose

**Comment by ossecowner** [comment]
hi @jm404

 I did what you said. 
**a**. for SCA:   my agents were members of two groups :soc and IT . SCA was ok only for one of them I add all agents to default group and it is ok now.
Ihave a question if I want do policy monitoring for special group , should I put policy file (.txt) in `/var/ossec/etc/shared/agent name group` only ? Is something else necessary?
**b**.  for open scap:  I did what you said. I have group. is it necessary  to write wodle of open-scap on `/var/ossec/etc/shared/agent name group/agent.conf` ? 
```
<wodle name="open-scap">
    <disabled>no</disabled>
    <timeout>1800</timeout>
    <interval>1d</interval>
    <scan-on-start>yes</scan-on-start>

  </wodle>

```
because by default it is disable.
I have ubuntu and centos so I can;t write this only in `<agent_config os="Linux"></...>` in agent.conf.
```
 <content type="xccdf" path="ssg-centos-7-ds.xml">
      <profile>xccdf_org.ssgproject.content_profile_pci-dss</profile>
      <profile>xccdf_org.ssgproject.content_profile_common</profile>
    </content>
```
I did theme but oscp don't work yet still.
thank you.

**Comment by jm404** [comment]
Hi @ossecowner,

I will split my answers following your naming convention:

**A**. Every file that you put on `/var/ossec/etc/shared/<AGENT_GROUP>/:` will be synced to the `/var/ossec/etc/shared/` agents that belong to that group.
If you create a new agent group, the folder generated for that group will not contain the policies files, so you have to copy them from `/var/ossec/etc/shared/default/`

Also, remember check that your SCA block of `/var/ossec/etc/ossec.conf` is activated (`<disabled>no</disabled>`)

Please note that you can distribute the `ossec.conf` file configuration also by using the [Centralized Configuration](https://documentation.wazuh.com/3.9/user-manual/reference/centralized-configuration.html) of Wazuh. Let me also mention the following [Agent Groups and Centralized Configuration](https://wazuh.com/blog/agent-groups-and-centralized-configuration/), which you may find useful.

**B**. SCA policies can be found on `/var/ossec/ruleset/sca`, it's not neccessary to copy them to the shared folder.

The configuration block that you set on `agent.conf` will override the agents `ossec.conf` as stated in [Precedence](https://documentation.wazuh.com/3.9/user-manual/reference/centralized-configuration.html#precedence). 


Agents by default have the `open-scap` disabled but contain the block related to it:

```
<wodle name="open-scap">
    <disabled>yes</disabled>
    <timeout>1800</timeout>
    <interval>1d</interval>
    <scan-on-start>yes</scan-on-start>

    <content type="xccdf" path="ssg-centos-7-ds.xml">
      <profile>xccdf_org.ssgproject.content_profile_pci-dss</profile>
      <profile>xccdf_org.ssgproject.content_profile_common</profile>
    </content>
  </wodle>
```

So if want to activate it wodle you can write the following in the `agent.conf`

```
<agent_config os="Linux">
	<wodle name="open-scap">
	    <disabled>no</disabled>
	</wodle>
</agent_config>
```

That, will override the setting in the Agent, activating the wodle.

You can get more info about it at: [Centralized Configuration process](https://documentation.wazuh.com/3.9/user-manual/reference/centralized-configuration.html#centralized-configuration-process)


Best regards,

Jose

**Comment by ossecowner** [comment]
hi @jm404
i did configuration of SCA,open scap, CIS CAT such as you said.
I have two group and they are member of default group too. sca works and show data in kibana for one of group but for other group  I see this only :

![sca](https://user-images.githubusercontent.com/50073170/60952076-c8c98e00-a30f-11e9-8ac3-b784556c8e63.png)

` in /var/ossec/ets/shared/default/agent.conf   for more confidence:`

![wwwwwwww](https://user-images.githubusercontent.com/50073170/60952261-2f4eac00-a310-11e9-9684-e1eb60521744.JPG)

and the result of cat`cat /var/ossec/logs/ossec.log | grep oscap` : 

![image](https://user-images.githubusercontent.com/50073170/60952687-f5ca7080-a310-11e9-9a4a-f85f4ed51314.png)

the group that I can't see it's sca result is behind nat.
i don't know it's reason.

**Comment by ossecowner** [comment]
Can someone help me?

**Comment by jm404** [comment]
Hi @ossecowner,

Sorry for the late response,

Regarding to this photo:

![image](https://user-images.githubusercontent.com/46649922/61106727-490e0180-a47e-11e9-8e80-4feb73f1300c.png)
****

You shouldn't specify both policies `cis_debian_linux_rcl.yml` and
`cis_rhel7_linux_rcl.yml` because this way, manager is configuring agents to run both, which is not desirable since the Debian policy doesn`t make sense on CentOS and RHEL OS and vice versa.

When installing, Wazuh-Agents detect the OS and configure it properly, just remove those policies from `agent.conf` and make sure the `ossec.conf` does have the policy related to it's OS.

----------------------------

Is there any particular reason for installing Logstash? I mention this because it`s not needed for Wazuh in Elastic 7.x.

Can you check if `open-scap` is properly configured on Agents by checking their `ossec.conf` file? Also check logs of the agents to see if there is any warning or error

Let me also mention you our [OpenSCAP](https://documentation.wazuh.com/3.x/user-manual/capabilities/policy-monitoring/openscap/how-it-works.html#requirements) guide for installation and configuration.

Best regards,

Jose

**Comment by ossecowner** [comment]
Dear @jm404 
I configured sca and oscap Just like what you said and is in wazuh documentation.
oscap don't work on none of them.

in /var/ossec/etc/shared/default/agent.conf:
```
 <wodle name="open-scap">
        <disabled>no</disabled>
  </wodle>
```

and sca work for internal agents ,that they are in range of manager IP. and it don't work on agents are behind **NAT** , Those that are in **different IP range**.

wazuh=3.9.2 agents=9.2& 9.3 elastikstack=7.2
**Basic license** is active.
I installed logstash before for ELK 6 not now. 
 Thank you.

**Comment by jm404** [comment]
Hi @ossecowner,

Sorry, maybe you misunderstood my answer. The code on `agent.conf` must also have the `agent_config` parameter  (I did not included it as it can vary) like the following:

```
<agent_config os="Linux">
    <wodle name="open-scap">
       <disabled>no</disabled>
    </wodle>
</agent_config>
```

Also, make sure that you can reach your agents in the different nat by pinging from manager to them

Regarding your last paragraph, let me mention that managers are not guaranteed to work with agents that have a superior version, please see [Product Compatibility](https://documentation.wazuh.com/3.x/installation-guide/compatibility_matrix/index.html#product-compatibility) so please either upgrade Manager to 3.9.3 or downgrade Agents to 3.9.2.

Best regards,

Jose

**Comment by ossecowner** [comment]
Yes, I always study wazuh.com before configuration, the code on agent.conf have the agent_config parameter. Ok I check your suggestion about compatibility

**Comment by ossecowner** [comment]
Hi @jm404
I solved the problem. when I copy the policy in new file and put it in /var/ossec/etc/shared/default and get to it permission to ossec  as owner and copy txt file of that policy in new file , sca works good and after it I can delete those new files and sca still works  . It's BUG  of wazuh.
thank you.
