### ISSUE TITLE
transfer client.key to another wazuh server

### ISSUE THREAD

**Issue by ossecowner** [wazuh/wazuh-puppet#148]
@manuasir  @jm404 @jesuslinares 
Hello dear
I reinstalled wazuh  With the same address as before and I copied the previous "client.key" file to new wazuh. after transter keys I see that agents are active and work good but when I type:
`systemctl restart wazuh-manager.service` 
it clears the inside of the client.key file 🤕 and I don't see anything on Kibana in the agent section.
please help me. Why this is happening ? how can I solve it?
thank you.

**Comment by jm404** [comment]
Hi @ossecowner ,

The `client.keys` will be overridden if you copy it when  Wazuh-Manager is running.

In order to successfully restore the agents:

- Stop the wazuh manager:

```
systemctl stop wazuh-manager
```

- Copy the old `client.keys` file

- Ensure permissions and owner are correct:
```
chmod 640 /var/ossec/etc/client.keys && chown root:ossec /var/ossec/etc/client.keys
```

- Start the Wazuh-Manager

```
systemctl start wazuh-manager
```

This way, when starting up, the Manager will read the new `client.keys` file.

I hope this helps to solve your problem, let me know if need further help.

Best regards!

Jose

**Comment by ossecowner** [comment]
dear @jm404 
thank you,I did what you said and now it's ok .
Thank you very much 👍

**Comment by jm404** [comment]
Hi @ossecowner,

Glad to help! Don't hesitate to ask us anytime about anything you need.

Best regards!

Jose

**Comment by mbmakmur** [comment]
hey guys, Hi @jm404  I had a similar situation like @ossecowner 
except for copying key file from old server, I had the key copied directly from client.key file on agent and then pasted to the client.key file on wazuh server (while the wazuh server is stopped).

Everything seems working after that, but I the agent registration date = 1970/01/01 08:00:00 at the agent's page on kibana. 
Is that OK? (I know I must have skipped a process or two by copying keys like this)

By the way, how do I change/update agent keys?

Thank you

**Comment by mbmakmur** [comment]
Hi @jm404 

Thank you for responding. I'm using neither Docker nor Puppet for this case. Also, for this case I'm using Wazuh 3.11.4 on single server architecture comprising EFK stack 7.6.0

Thank you, looking forward to your advise. Btw, will this break anything other than the registration date

**Comment by jm404** [comment]
Hi @mbmakmur ,

Could you check the content of `/var/ossec/queue/agents-timestamp`? It should show you some output like the following:

```
[root@ip-10-0-x-xx wazuh]# cat /var/ossec/queue/agents-timestamp 
001 Debian 54.xxx.xxx.xx 2020-03-25 09:20:41
002 Ubuntu 54.xxx.xxx.xxx 2020-03-25 09:20:47
003 Amazon 52.xxx.xxx.xxx 2020-03-25 09:21:09
004 Centos 184.xxx.xxx.xxx 2020-03-25 09:21:09
005 Windows 13.xxx.xxx.xxx 2020-03-25 09:21:24
006 RHEL7 54.xxx.xxx.xxx 2020-03-25 09:21:31

```

If it's corrupt or empty, the best solution is to re-register the Agents so the timestamp will be restored, you can do it automatically with any Deployment technology like `Ansible`, `Puppet` or `Chef`

Best regards,

Jose

**Comment by mbmakmur** [comment]
Hi @jm404 

Thank you for responding and the guidance given. Really appreciate it!

What actually happened was I did not have any agents registered on the wazuh manager and made a image backup for that instance. Now the active instance had more complicated issues so I am using the backup (which was made before any agents were linked)

I don't have many agents for this exercise and doing this manually for now (i.e. no Ansible, etc). Since previously no agents were registered, when I checked `/var/ossec/queue/agents-timestamp` the file you mentioned was not created yet. So I created the file and put in the record with dates. I booted up the wazuh manager and everything is OK so far, though the first agent still has the registration date dated in 1970, others are showing correct date. 
My only concern is if this will break anything in the future? If it's just date issue for showing in Kibana, I'm good with that at least for now. Please advise

Also, how do I re register the agents, do I remove first from server i.e by reversing the process above and run WAZUH_MANAGER_IP='x.y.a.b' ?

Thank you !

**Comment by jm404** [comment]
Hi @mbmakmur,

In order to re-register it's not required to remove the Agents, you can simply re-register them and the client.keys will be updated automatically

Sorry for the late response, let us know if you need further help

Best regards,

Jose

Sorry for the late
