### ISSUE TITLE
create dashboard in kibana

### ISSUE THREAD

**Issue by ossecowner** [wazuh/wazuh-puppet#154]
hello
I want to make a dashboard for result of "free -h". I wrote wodle,decoder,rule and they are ok.
and I see  this:
![memory usage](https://user-images.githubusercontent.com/50073170/64488160-67337c00-d1f9-11e9-8197-e9abfdaf9b13.png)

how can I create visualization that show entire these field as number. what visualization type? 
or how can I use timelion ? it's wrong when I writte:
![aa](https://user-images.githubusercontent.com/50073170/64488244-9f878a00-d1fa-11e9-9bb9-01175fef228c.png)

 can you guide me?
thank you.

**Comment by jm404** [comment]
Hi @ossecowner,

I noticed you using a filed `cpu-usage` which is not stated in your previous screenshot. Anyway, I configured a decoder and when selecting one of my fileds I found the following error:

![image](https://user-images.githubusercontent.com/46649922/64518226-1489bb00-d2f2-11e9-86dc-ef46c1fa7e72.png)

This is caused because the added fields are mapped as `keyword`, so numeric operations can't be applied.

It's required to update the mapping to the new objects. We are investigating about how to correctly map the new fields.

Maybe you can find useful the [Elastic Mapping Documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html)

Best regards,

Jose

**Comment by ossecowner** [comment]
Yes the second screenshot is wrong I mean max:data.used-RAM. 
OK,thanks.
