### ISSUE TITLE
ossec "match" tags in rules

### ISSUE THREAD

**Issue by ossecowner** [wazuh/wazuh-puppet#159]
hi 
can you guide me? I don't know when shoud I close single quotation in match tag .I have read rules of ossec , in some of them it is closed and in another  it's not closed.
![1](https://user-images.githubusercontent.com/50073170/66254711-1034ae80-e787-11e9-887b-574c40712cdd.png)
I am confused.
thank you.

**Comment by Zenidd** [comment]
Hi @ossecowner 

> can you guide me? I don't know when shoud I close single quotation in match tag .I have read rules of ossec , in some of them it is closed and in another it's not closed.

The rules in your example above(and generally the ones with quotations in `0015-ossec_rules.xml` file) are rules related to  `<command>` blocks. 
**Let's see it with an example:**

- The rule 531 expects match with `ossec: output: 'df -P': /dev/`
```
  <rule id="531" level="7" ignore="7200">
    <if_sid>530</if_sid>
    <match>ossec: output: 'df -P': /dev/</match>
    <regex>100%</regex>
    <description>Partition usage reached 100% (disk space monitor).</description>
 <group>low_diskspace,pci_dss_10.6.1,gpg13_10.1,gdpr_IV_35.7.d,hipaa_164.312.b,nist_800_53_AU.6,</group>
  </rule>
```

- This localfile command stanza launches `df -P` each 10 seconds. 

```
  <localfile>
    <log_format>command</log_format>
    <command>df -P</command>
    <frequency>10</frequency>
  </localfile>
```

- This is the event generated. You can see it in /var/ossec/logs/archives/archives.log enabling `<logall>` in `ossec.conf`

```
2019 Oct 08 13:21:32 vagrantWorker->df -P ossec: output: 'df -P': udev                   3995464         0     3995464        0% /dev
2019 Oct 08 13:21:32 vagrantWorker->df -P ossec: output: 'df -P': tmpfs                  4036152         0     4036152        0% /sys/fs/cgroup
2019 Oct 08 13:21:32 vagrantWorker->df -P ossec: output: 'df -P': tmpfs                  4036152    403648     3632504       11% /dev/shm
2019 Oct 08 13:21:32 vagrantWorker->df -P ossec: output: 'df -P': tmpfs                     5120         4        5116        1% /run/lock
2019 Oct 08 13:21:32 vagrantWorker->df -P ossec: output: 'df -P': /dev/loop1              144128    144128           0      100% /snap/gnome-3-26-1604/92
2019 Oct 08 13:21:32 vagrantWorker->df -P ossec: output: 'df -P': /dev/loop3               55808     55808           0      100% /snap/core18/1144
2019 Oct 08 13:21:32 vagrantWorker->df -P ossec: output: 'df -P': /dev/nvme0n1p2       244568380 152484776    79590548       66% /
```
_The output event includes quotations in `'df -P'` and that's why the rule has also the quotations._

**Another example. The unclosed quotation in the rule below is probably a typo:**
```
  <rule id="533" level="7">
    <if_sid>530</if_sid>
    <match>ossec: output: 'netstat listening ports</match>
    <check_diff />
    <description>Listened ports status (netstat) changed (new port opened or closed).</description>
    <group>pci_dss_10.2.7,pci_dss_10.6.1,gpg13_10.1,gdpr_IV_35.7.d,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AU.6,</group>
  </rule>
```

This is the event that the rule above wants to match. 
```
  2019 Oct 08 13:25:42 vagrantWorker->netstat listening ports ossec: output: 'netstat listening ports':

It would match with both 
    <match>ossec: output: 'netstat listening ports</match>
and
    <match>ossec: output: 'netstat listening ports'</match>
```
In this particular case the expected events include quotations but in general, the `<match>` field doesn't necessarily include quotations.

Greetings, JP Sáez

**Comment by Zenidd** [comment]
Let me know if you want some help on writing custom rules or want to delve a little deeper in the rules you referred above.

**Comment by ossecowner** [comment]
@Zenidd 
thank you.

**Comment by Zenidd** [comment]
You are welcome, let me know if you need something else @ossecowner 

Greetings, JP Sáez
