### ISSUE TITLE
Automatic rollout problem

### ISSUE THREAD

**Issue by philsynek** [wazuh/wazuh-puppet#22]
Hello,

I have a problem, which might be my fault but I don't find the error.

We added the following to our node manifest:

`class { "wazuh::client":
    ossec_server_ip => "W.X.Y.Z"
  }`

After the puppet run we see on the server:`2017/05/31 13:14:12 ossec-remoted(1213): WARN: Message from 'A.B.C.D' not allowed.` and on the agent:`2017/05/31 14:45:57 ossec-agentd(4101): WARN: Waiting for server reply (not started). Tried: 'W.X.Y.Z'.`

After manually running `/var/ossec/bin/agent-auth -m W.X.Y.Z`on the agent it works and I see the agent registration in Kibana. Would be no problem for us to run this command on rollout, if we could determine that the agent is already registered. Because if I run it twice I see duplicates on the server side with an appending "2". So I don't want to run this command, when the agent is already registered.

Is there any way to do this?
Thank you!
Phil

Edit: Unfortunately I just saw, that the status of the connected agent (after manual procedure) is "never connected". So the manual setup does not work either. Additionally I saw, that the agent cannot connect to the server. It authenticates and gets a key, but afterwards I see messages like: `2017/05/31 16:05:41 ossec-agentd(4101): WARN: Waiting for server reply (not started). Tried: 'W.X.Y.Z'.` Yes UDP 1514 is open and the server is listening.

**Comment by jlruizmlg** [comment]
Hi @philsynek, 

You run puppet in the manager after the agent installation?

When you ran the wazuh client class, the client.keys is autogenerated in the client side, then we use exported resources to store this client.keys in the Puppet database, but at this point the manager doesn't know about the new client.keys (this is why you have the message ```017/05/31 13:14:12 ossec-remoted(1213): WARN: Message from 'A.B.C.D' not allowed.```)

In order to finish the installation, you need to run Puppet again in the manager, in this case, puppet should take the agent or agents keys information from the database and apply in the manager, and at this moment your client should be connected and running.

We are working now in the [ossec-authd](https://github.com/wazuh/wazuh-puppet/blob/master/manifests/server.pp#L145) option, in a few days you will can choose which option is better for you.

Thanks for your comments!

**Comment by philsynek** [comment]
Okay, this explains the "not allowed" messages, thank you! No I am not running puppet on the master. I set the master up by hand. I will check into this!

Do you have an idea why the communication does not work, as explained in my edit section above?

Thank you!
Phil

**Comment by jlruizmlg** [comment]
The log show this message usually in two cases

1. The agent has not communication with the manager (in your case as you said in your section above all communications, ports, etc, should be correct)
2. The client.keys is not correct: please review before run Puppet again the client.keys in the agent is present in the manager, why you should review that?, Exported resources overwrite all your configurations, so if you ran puppet after use agent-auth to take the client.keys, maybe your client.keys has been overwrite by Puppet.

If all looks correct, please run ossec-remoted in debug mode ```/var/ossec/bin/ossec-remoted -d``` or in the file /var/ossec/etc/internal_options.conf change to level 2 the option ```remoted.debug=0``` and restart the agent, you can do the same in the manager in order to have more information about what's happening.

**Comment by jlruizmlg** [comment]
hi @philsynek have you any feedback about this issue? Thanks!!

**Comment by philsynek** [comment]
Hi!
I am sorry... we actually moved away from puppet to ansible... this is why I haven't been able to test it. Sorry!

Kind regards,
Phil

**Comment by jlruizmlg** [comment]
Hi @philsynek no problem at all! Btw soon we will go to releease our ansible
