### ISSUE TITLE
Windows computers with renamed "Administrator" account fail to install agent

### ISSUE THREAD

**Issue by mike406** [wazuh/wazuh-puppet#362]
On line 285 of wazuh::agent class there is no need to set owner to Administrator when you already are using Administrators for group. Many organizations choose to rename their Administrator account to something else as a security practice which causes the Puppet run to fail. Set owner to 'Administrators' instead.

Same applies to line 441 in  wazuh::params_agent

After changing 'Administrator' to 'Administrators' in these two places I have success installing the agent.

**Comment by mike406** [comment]
Noticing this has the unfortunate consequence of ossec.conf always having its mode modified, not sure why though. Every run logs mode changed '0664' to '0644' (corrective), will need to do more testing to get that to stop.

**Comment by c-bordon** [comment]
Hi Mike, I've been running local tests to replicate what you mention, and that's correct, I was able to get the same error.
For security reasons we have to consider an option a little more restrictive than the one you propose since we do not consider that giving permissions to all administrator users is the safest, so we are going to add this topic to the backlog and we will work on finding that one solution.
Thank you very much for creating this issue that allows us to improve our repositories

**Comment by mike406** [comment]
Hi @c-bordon, the way the manifest is defined by default already does grant access to all Administrators. This is made so because of the “group => ‘Administrators’” line. My changes do not make it any more or less secure as I am not granting new permissions, only removing the redundant line of adding the “Administrator” user.

**Comment by c-bordon** [comment]
Hello Mike, thanks for your answer, we have been reviewing the process again and carrying out new tests, and we conclude that what you commented is correct.

We make the corrections that you mention in the following PR:
https://github.com/wazuh/wazuh-puppet/pull/419
https://github.com/wazuh/wazuh-puppet/pull/420
