### ISSUE TITLE
wazuh agent in default role (without breaking wazuh server)

### ISSUE THREAD

**Issue by maltfield** [wazuh/wazuh-puppet#47]
Hi,

What is the proper way to include the wazuh agent in the "common" profile (for the "default node") without breaking the puppet-provisioned wazuh server?

Currently, I"m getting the following error:

	root@test:~# puppet agent -t
	Info: Using configured environment 'dev'
	Info: Retrieving pluginfacts
	Info: Retrieving plugin
	Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: Class[Wazuh::Repo] is already declared in file /etc/puppet/code/environments/dev/modules/wazuh/manifests/client.pp:54; cannot redeclare at /etc/puppet/code/environments/dev/modules/wazuh/manifests/server.pp:64 at /etc/puppet/code/environments/dev/modules/wazuh/manifests/server.pp:64:5 on node test.localdomain
	Warning: Not using cache on failed catalog
	Error: Could not retrieve catalog; skipping run

Our puppet Main Manifest uses [hiera_include('classes')](https://docs.puppet.com/hiera/1/puppet.html#assigning-classes-to-nodes-with-hiera-hierainclude), and our hiera.yaml manifest's last entry in the hierarchy defines our "[default node](https://docs.puppet.com/puppet/latest/lang_node_definitions.html#the-default-node)" to use the the "default" role (which simply includes the "common" profile), which is used by all our puppet clients (it adds our users, sets up ssh, basic packages, ntp, syslog, and all the basics that we want on *all* our nodes--now including the wazuh client)

According to the hiera_include() documentation, using this setup means that nodes will get *all* classes that match it in the hierra hierarchy:

 * https://docs.puppet.com/hiera/1/puppet.html#assigning-classes-to-nodes-with-hiera-hierainclude

So, in our case, our Wazuh Server gets the "common" role and the "wazuhmanager" role. The common role calls the class "wazuh::client" and the "wazuhmanager" role calls the class "wazuh::server". This creates at least 1 conflict since, for example, both classes call "wazuh::repo".

Is this a bug in how the wazuh puppet module is written? Or am I doing something wrong?

Surely it's common for people to define the wazuh client class in their common role. Please let me know how this is expected to be done without breaking the wazuh manager role.

**Comment by mjflve** [comment]
Hi @maltfield,

Sorry for the late reply.

A workaround could be to remove the `wazuh::client` from hiera and include it into your main manifest, you should still have the ability to set the necessary variables in hiera. Let me try to explain this with the following example:

**hieradata/common.yaml:**
```
---
classes:
  - ntp

wazuh::client::ossec_server_ip: '192.168.209.166'

ntp::servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
  - 3.pool.ntp.org
```
**hieradata/nodes/manager.example.com.yaml**
```
wazuh::server::smtp_server: 'localhost'
wazuh::server::ossec_emailto:
  - 'user@mycompany.com'
  - 'user2@mycompany.com'
```

**manifests/site.pp:**
```
hiera_include('classes')

node "default" {
  include wazuh::client
}

node "manager.example.com" {
  include wazuh::server
}
```

With the above you should be able to run the `wazuh::client` in your default node, and include `wazuh::server` in the nodes you need it. Meanwhile, we are working on refactoring this module in order to fix this kind of behavior.

I hope it helps.

Best regards,

**Comment by hex2a** [comment]
Hi,

since the [knockout prefix](https://www.devco.net/archives/2016/03/13/the-puppet-4-lookup-function.php) parameter does not seem to be used for the "unique" lookups/hiera_include, it can't be easily removed from the `classes` array without a workaround.

Workaround:
https://tickets.puppetlabs.com/browse/PUP-7428?focusedCommentId=433345&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-433345

As described in the ticket, the `wazuh::client` class can then be removed in the hiera node config for the manager node by prefixing it with REMOVE_
e.g.:
```
classes:
  - REMOVE_wazuh::client
  - wazuh::server
```
