### ISSUE TITLE
After deploying the Wazuh agent for Windows it is not automatically started

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh-puppet#470]
### Description

After doing some testing on the Wazuh cluster and agents deployment with Puppet, we identified an issue in Windows agents. Basically, when the agent is deployed, the service is not started and the user should start it manually.

In addition, the service was in `disabled` state so, we had to manually set the service as `enabled` to then start it.

**Comment by okynos** [comment]
Hello!

After test the 4.2.6 version with a simple manifest
```
node "win-60e1afm9cn4.home" {
  class { 'wazuh::agent':
    wazuh_register_endpoint => "xxx.xxx.xxx.xxx",
    wazuh_reporting_endpoint => "xxx.xxx.xxx.xxx"
  }
}
```
We can conclude that there is some setting that perform the service to not start. An specific variable that changes such behaviour is `manage_client_keys` https://github.com/wazuh/wazuh-puppet/blob/4.3/manifests/agent.pp#L485
This variable manage the daemon start or not in addition with the agent registration through the manager. So if you used such variable or changed its value it is an expected behaviour.

We have tested the default procedure with service started and running as a normal installation.
4.2.6 started and working
![image](https://user-images.githubusercontent.com/10661307/161521734-dbee253c-4d7f-4018-a6ea-59793cc5462f.png)
![image](https://user-images.githubusercontent.com/10661307/161522605-912cf5bd-df80-44c5-8d51-555f387ed778.png)

4.3.0 started and working
![image](https://user-images.githubusercontent.com/10661307/161525309-98030aff-c5c3-4aaf-99e9-284db9c499b6.png)
![image](https://user-images.githubusercontent.com/10661307/161525380-f1c6101f-675a-4b62-80af-ed034ff140cf.png)


In another part of the test we have detected some syntax error that we will describe here https://github.com/wazuh/wazuh-puppet/issues/473
