### ISSUE TITLE
supported operating systems?

### ISSUE THREAD

**Issue by maltfield** [wazuh/wazuh-puppet#52]
Hi,

Where can I find a list of supported Operating Systems (& Linux Distributions) for this puppet module?

More specifically, could this list differ for agent & manager? Does it support Debian?

I successfully installed a wazuh manager on a Debian 9 server manually, but when I attempt to do so with this puppet module, I get the following error from puppet:

    Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Module wazuh is not supported on Debian at /etc/puppet/code/environments/dev/modules/wazuh/manifests/params.pp:74:11 on node test.localdomain
    Warning: Not using cache on failed catalog
    Error: Could not retrieve catalog; skipping run

Please let me know where I can find a published list of Operating Systems (& Linux Distributions) supported for the wazuh agent, wazuh manager, wazuh agent puppet module, and the wazuh manager puppet module.

**Comment by mjflve** [comment]
Hi @maltfield,

You can find the compatibility list into the [forge module information](https://forge.puppet.com/wazuh/wazuh/compatibility), we going to release a new version with various fixes and enhancements soon: https://github.com/wazuh/wazuh-puppet/blob/master/CHANGELOG#L280-L296

In the following links you can find more information regarding of the wazuh-agent and wazuh-manager package compatibility: 

Wazuh Agent:
[Debian](https://documentation.wazuh.com/current/installation-guide/installing-wazuh-agent/wazuh_agent_deb.html#adding-the-wazuh-repository)
[RPM](https://documentation.wazuh.com/current/installation-guide/installing-wazuh-agent/wazuh_agent_rpm.html#adding-the-wazuh-repository)

Wazuh Manager:
[Debian](https://documentation.wazuh.com/current/installation-guide/installing-wazuh-server/wazuh_server_deb.html#adding-wazuh-repositories)
[RPM](https://documentation.wazuh.com/current/installation-guide/installing-wazuh-server/wazuh_server_rpm.html#adding-the-wazuh-repository)

This issue seems like the puppet agent is unable to detect the Debian codename, could you confirm you have lsb-release installed on your Debian machine? thanks!

Best regards,

**Comment by maltfield** [comment]
Hey, thanks for the response.

Indeed, it was lsb-related. We found that installing 'lsb-core' on our system fixed the issue, and now the puppet manager installs itself fine via this puppet module.

    root@localhost:~# apt-get install lsb-core
    ...
    root@localhost:~# lsb_release -a
    No LSB modules are available.
    Distributor ID: Debian
    Description:    Debian GNU/Linux 9.1 (stretch)
    Release:        9.1
    Codename:       stretch

Thanks!
