### ISSUE TITLE
How to manage client.keys with this puppet module

### ISSUE THREAD

**Issue by maltfield** [wazuh/wazuh-puppet#58]
Hello,

What is the recommended way to manage the client.keys file using this puppet module?

The traditional way to add a client to the server in OSSEC is described here:

 * https://ossec-docs.readthedocs.io/en/latest/manual/agent/agent-management.html

The equivalent wazuh-specific method is described here for the CLI:

 * https://documentation-dev.wazuh.com/current/user-manual/agents/command-line/register.html

Or via authd or wazuh api:
 * https://documentation-dev.wazuh.com/current/user-manual/registering/use-registration-service.html
 * https://documentation-dev.wazuh.com/current/user-manual/agents/restful-api/register.html

But let me back-up: I spent a few days trying to figure out why, when using this puppet module, my clients would disconnect from the master. The telltale sign is that the entry in `/var/ossec/etc/client.keys` would disappear.

The client would say:

```
2017/12/27 20:14:10 ossec-agentd(4102): INFO: Connected to the server (10.0.0.1:1514).
...
2017/12/27 22:33:42 ossec-agentd(1218): ERROR: Unable to send message to server.
```

And the server would say:

```
2017/12/27 20:26:12 wazuh-modulesd:database: DEBUG: Synchronizing agents.
2017/12/27 20:26:12 wazuh-modulesd: ERROR: (1401): Error reading authentication key: '
'.
2017/12/27 20:26:12 wazuh-modulesd: DEBUG: (1751): File client.keys not found or empty.
2017/12/27 20:26:12 wazuh-modulesd:database: DEBUG: Agent sync completed.
```

And using the ossec-puppet client, it would be similar:

```
2017/12/26 22:06:13 ossec-remoted(1410): INFO: Reading authentication keys file.
2017/12/26 22:06:13 ossec-remoted(1401): ERROR: Error reading authentication key: '
'.
2017/12/26 22:06:13 ossec-remoted(1750): ERROR: No remote connection configured. Exiting.
```

But the real issue was that this puppet module, by default, will overwrite the server's `/var/ossec/etc/client.keys` file with the contents of a single newline character.

I'm posting this question because I'm very shocked by the above behaviour. Why is the default, ootb behaviour of this puppet module to clobber the contents of the client.keys file? If this is the default behaviour, I would expect there to be documentation on how to manage this file in puppet, but I couldn't find such a document.

What is the recommended way to exchange keys with the manager & client when adding a new client? And what is the recommended way to do so that updates the client.keys file in puppet?

If we don't have a clear guide on this, can we please make the default value for `manage_client_keys` set to `false`?

**Comment by jlruizmlg** [comment]
Hi @maltfield sorry for the late response, let me explain the two options that you have with this module.

1. Export Resources: By default, we use Puppet export resources to control the client.keys. 
The client.keys is generated in the agent and saved in a database, then the next time that the puppet runs in the manager, Puppet builds the client.keys with the agent's key, with this option you always keep a backup from your client.keys and agents/manager status in your Database: 

https://github.com/wazuh/wazuh-puppet/blob/master/manifests/client.pp#L125
 https://github.com/wazuh/wazuh-puppet/blob/master/manifests/server.pp#L147

2. Agent authd: With this option, Export Resources is not needed, with auth enabled, the agents run agent-authd against the manager to obtain the client.keys, in this way you have the option to add agents manually as well since the Resources overwrite the client.keys in the manager.

https://github.com/wazuh/wazuh-puppet/blob/master/manifests/server.pp#L167
https://github.com/wazuh/wazuh-puppet/blob/master/manifests/client.pp#L140 

If you have the default configuration probably this is why our client.keys is overwritten because Export Resources is the default configuration.

**Comment by jsnod** [comment]
We've come across this as well.  We attempted to use the default Export Resources option, but it appears that MySQL support has been removed from this module?  We ended up setting `manage_client_keys => false` on both server and clients, and are manually adding agents per the instructions at https://documentation-dev.wazuh.com/current/user-manual/agents/command-line/register.html

Not ideal, as we used to run an older version of `wazuh-ossec` and it seemed to work fine with the puppet module managing all client keys.  

@jlruizmlg can you elaborate on the database you mention above?  Where/how are client keys stored if there isn't a way to configure a DB connection anymore?

**Comment by jm404** [comment]
Hi @minorOffense, @jsnod, @maltfield,

Sorry for the very late response,

When managing Agents on Wazuh, writing directly on `client.keys` is completely discouraged since it could lead to wrongly generated or duplicated id/keys. 

Also, the ID of the agents was generated randomly, which doesn't provide consistency on successive registered agents. As a consequence of the previously stated reasons, the `export` option has been removed in the new [Puppet Release](https://github.com/wazuh/wazuh-puppet/tree/v3.9.2_7.1.1)

If a manual registration is desired, you can make use of [Command Line Interface](https://documentation.wazuh.com/3.9/user-manual/registering/using-command-line.html#using-command-line) for Windows, Linux, MacOS and Unix hosts.

There are different registration options from manual to automatic registration, including encryption and passwords to properly secure the process. You can check all them at [Registration Methods](https://documentation.wazuh.com/3.9/user-manual/registering/registration-process.html#registration-methods)

In any case, we are always open to new requests and ideas/discussion so feel completely free to share if stated registration method suits your needs.

Best regards,

Jose

**Comment by jm404** [comment]
Hi @minorOffense, @jsnod, @maltfield,

I just wanted to follow up on this issue, Did you tried the new agent registration method?

Let me know if you found it useful or if you want to add some changes.

Best regards,

Jose
