### ISSUE TITLE
Virus total connection error in Wazuh

### ISSUE THREAD

**Issue by Muneeb93** [wazuh/wazuh-puppet#638]
Hi,
I use virustotal in wazuh, and it is not working as expected kibana don't show any thing.
I have set this config in ossec.conf in manager:

 `<integration>`
  `<name>virustotal</name>`
  `<api_key>......................</api_key>`
  `<group>syscheck</group>`
  `<alert_format>json</alert_format>`
 `</integration>`
 
it has no other specific settings, I don't know why it doesn't work!!!!!!!! Also my wazuh is behind a proxy server so I have alerady configured my proxy setting in yum.conf and also defined a nameserver 8.8.8.8 in resolve.conf file. please help.

I have attached the ossec.log error as well for the reference.
![1](https://user-images.githubusercontent.com/32594715/216515337-e4fb9756-6f2a-4d38-a9e2-f027bc9a3f8e.png)

**Comment by vcerenu** [comment]
Hello @Muneeb93 

Due to the error that is generated, the problem may be your connection to the Virustotal API.

Try testing your API connection using a `cURL` command in a command window on the server where `Wazuh manager` is located.
```
# curl https://www.virustotal.com/vtapi/v2/file/report -F resource=<SHA256-for-file-into-DB> -F apikey=<vt-api-key>
```

If connectivity is present and the `API` key is valid, a file report will be returned in `JSON` format.
