### ISSUE TITLE
Move command and email_alert template fragments

### ISSUE THREAD

**Issue by weavage** [wazuh/wazuh-puppet#71]
Was digging through the module and noticed that the template fragments 'command.erb' and 'email_alert.erb' are under templates directory instead of templates/fragments. Since these are concat::fragment's similar to localfile, shouldn't they be moved to templates/fragments? Would also need a minor edit to the template path in the respective manifests.

**Comment by Zenidd** [comment]
Hi @weavage,

Thank you very much for this improvement suggestion. We really appreciate the time you took to think about it and seems like it will make wazuh-puppet cleaner and will increase his file hierarchy readability. We are going to review this improvement, work on it when possible and we will add it to Wazuh-puppet.

Again, thanks for your contribution.



<br></br>
Best regards,

Juan Pablo Sáez

**Comment by jm404** [comment]
Hi @weavage,

Sorry for the late response, 

After reviewing your proposal, it makes sense to have the `command.rb` and `default_commands.rb` contained under the *fragments* template like it happens with all other similar blocks that configure the `ossec.conf ` file

In order to do this, some tasks must be done:

- [ ] Move the templates to the `/fragments` folder

- [ ] Check references and fix them

- [ ] Test changes with default and custom commands

Best regards

Jose

**Comment by rshad** [comment]
Hi all!

Created new branch to test the required changes before merging to a stable branch.

https://github.com/wazuh/wazuh-puppet/tree/3.9.4_7.2.0_issue_71

Kr,

Rshad

**Comment by rshad** [comment]
Hi all,

The tests have been passed successfully!

Kind Regards,

Rshad

**Comment by jm404** [comment]
Done here #143 

Regards!
