### ISSUE TITLE
Error with the filebeat template

### ISSUE THREAD

**Issue by Tostti** [wazuh/wazuh-puppet#923]
During the test https://github.com/wazuh/wazuh/issues/21761, found an error in which the Filebeat template was apparently not being loaded after installing Wazuh via Puppet in Ubuntu 18.04. This caused an error in the health check of the Dashboard. 

![303103612-96404653-cdac-4546-87d2-e2925c950b3d](https://github.com/wazuh/wazuh/assets/42900763/ee376826-c11f-4827-bed0-dbfd5cbbe404)

I had to manually install the template to solve the issue.

**Comment by davidcr01** [comment]
# Update Report

## Investigation

I observed in this comment that the Filebeat module URL was not modified to perform the test:
https://github.com/wazuh/wazuh/issues/21761#issuecomment-1931868019

```pp

  archive { "/tmp/${$wazuh_filebeat_module}":
    ensure       => present,
    source       => "https://packages.wazuh.com/4.x/filebeat/${$wazuh_filebeat_module}",
    extract      => true,
    extract_path => '/usr/share/filebeat/module',
    creates      => '/usr/share/filebeat/module/wazuh',
    cleanup      => true,
    notify       => Service['filebeat'],
    require      => Package['filebeat'],
  }
```

Notice that the Wazuh Filebeat module URL is specified with `packages.wazuh.com/4.x` instead of `packages-dev.wazuh.com/pre-release`

**Comment by vcerenu** [comment]
The index that had been in yellow status was reviewed, the problem I had was that the replica number was at 1.

The value was changed to 0 and the status returned to green.

The cause of the error could be due to not having the Filebeat module in the first installation and installing it after building the entire stack.

When reinstalling, certain directories are not deleted with the apt remove command, which means that the FB module files, FB configuration, datafiles and Wazuh indexer logs are not deleted, so when you reinstall Wazuh it keeps the data previous ones and add new ones.

``` console
root@ip-172-31-43-103:~# apt remove wazuh-dashboard wazuh-indexer wazuh-manager filebeat --purge -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  filebeat* wazuh-dashboard* wazuh-indexer* wazuh-manager*
0 upgraded, 0 newly installed, 4 to remove and 80 not upgraded.
After this operation, 3011 MB disk space will be freed.
(Reading database ... 180200 files and directories currently installed.)
Removing filebeat (7.10.2) ...
Removing wazuh-dashboard (4.8.0-1) ...
Stopping wazuh-dashboard service... OK
Deleting PID directory... OK
Deleting installation directory... OK
Removing wazuh-indexer (4.8.0-1) ...
Stopping wazuh-indexer service... OK
Removing wazuh-manager (4.8.0-1) ...
(Reading database ... 67955 files and directories currently installed.)
Purging configuration files for wazuh-manager (4.8.0-1) ...
Purging configuration files for wazuh-dashboard (4.8.0-1) ...
 OK
Purging configuration files for wazuh-indexer (4.8.0-1) ...
Deleting configuration directory... OK
dpkg: warning: while removing wazuh-indexer, directory '/var/lib/wazuh-indexer' not empty so not removed
dpkg: warning: while removing wazuh-indexer, directory '/var/log/wazuh-indexer' not empty so not removed
Purging configuration files for filebeat (7.10.2) ...
dpkg: warning: while removing filebeat, directory '/etc/filebeat' not empty so not removed
dpkg: warning: while removing filebeat, directory '/usr/share/filebeat/module' not empty so not removed
Processing triggers for systemd (237-3ubuntu10.56) ...
Processing triggers for ureadahead (0.100.0-21) ...
root@ip-172-31-43-103:~# 
```

![image](https://github.com/wazuh/wazuh-puppet/assets/56500015/34e5ee18-e4c5-4169-96fa-931b237a42bd)
![image](https://github.com/wazuh/wazuh-puppet/assets/56500015/535c636d-c0d3-4b79-acc3-f2f805902346)

Despite not having properly cleaned the files, the reinstallation process did not generate errors

**Comment by davidcr01** [comment]
# Update Report

I have investigated this issue and I could not reproduce the problem. Maybe the deployment with Puppet was done in several intervals, and Filebeat created the indices before the Wazuh indexer.

In a clean machine with the correct configuration, the deployment was completed successfully, the alerts were generated correctly and all indices were in a green state:

![Screenshot from 2024-02-18 22-55-30](https://github.com/wazuh/wazuh/assets/72193239/96baac2d-44ad-4943-9315-7b63c1dcd616)
![Screenshot from 2024-02-18 22-59-25](https://github.com/wazuh/wazuh/assets/72193239/2bb903e1-dceb-48c6-992d-13f599eb80d7)
![Screenshot from 2024-02-18 22-59-43](https://github.com/wazuh/wazuh/assets/72193239/939e6f60-9489-4b58-956e-d41fe899565c)
